language: python
python:
- 2.7
- 3.6
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
install:
- pip install -U pip pip-tools
- pip install numpy scipy scikit-learn matplotlib logging joblib argparse h5py
- git clone https://github.com/aldro61/pyscm.git /tmp/pyscm && cd /tmp/pyscm/ && python setup.py install
script:
- python -m unittest discover

#notifications:
#  email:
#    on_success: change
#on_failure: change