language: python
python:
- 2.7
- 3.5
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
install:
- pip install -U pip pip-tools
- pip install numpy scipy scikit-learn==0.19 matplotlib joblib argparse h5py
- cd .. && git clone https://github.com/aldro61/pyscm.git && cd pyscm/ && python setup.py install && cd ../multiview-machine-learning-omis
- pip install -e .

script:
- python -m unittest discover

#notifications:
#  email:
#    on_success: change
#on_failure: change